language: rust

os: osx

rust:
  - 1.20.0
  - stable

env:
  global:
    - RUST_BACKTRACE=full
    - RUST_TEST_THREADS=1

matrix:
  fast_finish: true

script:
  - cargo build --verbose
  - cargo test --verbose
